name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e Push da imagem gerada
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizando animação da cobrinha"
          branch: output
